#include "hippomodel/region/DG/DGRegionSpec.h"

namespace hippomodel::DG {

DGRegionSpec makeDGRegionSpec() {
    DGRegionSpec spec;

    spec.groups = {
        {"EC_LEC", "IDranges/EC/LEC", "EC-LEC", true, NeuronSign::Excitatory},
        {"EC_MEC", "IDranges/EC/MEC", "EC-MEC", true, NeuronSign::Excitatory},
        {"DG_GC", "IDranges/DG/GC", "DG-GC", false, NeuronSign::Excitatory},
        {"DG_MC", "IDranges/DG/MC", "DG-MC", false, NeuronSign::Excitatory},
        {"DG_AAC", "IDranges/DG/AAC", "DG-AAC", false, NeuronSign::Inhibitory},
        {"DG_BC", "IDranges/DG/BC", "DG-BC", false, NeuronSign::Inhibitory},
        {"DG_BCCCK", "IDranges/DG/BCCCK", "DG-BCCCK", false, NeuronSign::Inhibitory},
        {"DG_HICAP", "IDranges/DG/HICAP", "DG-HICAP", false, NeuronSign::Inhibitory},
        {"DG_HIPP", "IDranges/DG/HIPP", "DG-HIPP", false, NeuronSign::Inhibitory},
        {"DG_MOPP", "IDranges/DG/MOPP", "DG-MOPP", false, NeuronSign::Inhibitory},
        {"DG_TML", "IDranges/DG/TML", "DG-TML", false, NeuronSign::Inhibitory},
    };

    spec.connections = {
        {"LEC_DGGC", "EC_LEC", "DG_GC", 1.0, 0.11, 0.204},
        {"MEC_DGGC", "EC_MEC", "DG_GC", 1.0, 0.11, 0.204},
        {"DGMC_DGGC", "DG_MC", "DG_GC", 1.0, 0.11, 0.0228},
        {"DGAAC_DGGC", "DG_AAC", "DG_GC", 1.0, 0.0, 0.24},
        {"DGBC_DGGC", "DG_BC", "DG_GC", 1.0, 0.0, 0.24},
        {"DGBCCCK_DGGC", "DG_BCCCK", "DG_GC", 1.0, 0.07, 0.24},
        {"DGHICAP_DGGC", "DG_HICAP", "DG_GC", 1.0, 0.07, 0.24},
        {"DGHIPP_DGGC", "DG_HIPP", "DG_GC", 1.0, 0.0, 0.24},
        {"DGMOPP_DGGC", "DG_MOPP", "DG_GC", 1.0, 0.0, 0.24},
        {"DGTML_DGGC", "DG_TML", "DG_GC", 1.0, 0.0, 0.24},
        {"DGGC_DGMC", "DG_GC", "DG_MC", 1.0, 0.11, 0.932},
        {"DGMC_DGMC", "DG_MC", "DG_MC", 1.0, 0.11, 0.0234},
        {"DGAAC_DGMC", "DG_AAC", "DG_MC", 1.0, 0.0, 1.3},
        {"DGTML_DGMC", "DG_TML", "DG_MC", 1.0, 0.0, 1.38},
        {"LEC_DGAAC", "EC_LEC", "DG_AAC", 1.0, 0.39, 0.097},
        {"MEC_DGAAC", "EC_MEC", "DG_AAC", 1.0, 0.39, 0.097},
        {"DGGC_DGAAC", "DG_GC", "DG_AAC", 1.0, 0.39, 0.377},
        {"DGMC_DGAAC", "DG_MC", "DG_AAC", 1.0, 0.39, 0.0356},
        {"DGBC_DGAAC", "DG_BC", "DG_AAC", 1.0, 0.0, 0.3},
        {"DGBCCCK_DGAAC", "DG_BCCCK", "DG_AAC", 1.0, 0.07, 0.3},
        {"DGHICAP_DGAAC", "DG_HICAP", "DG_AAC", 1.0, 0.07, 0.3},
        {"DGHIPP_DGAAC", "DG_HIPP", "DG_AAC", 1.0, 0.0, 0.245},
        {"DGMOPP_DGAAC", "DG_MOPP", "DG_AAC", 1.0, 0.0, 0.3},
        {"DGTML_DGAAC", "DG_TML", "DG_AAC", 1.0, 0.0, 0.245},
        {"LEC_DGBC", "EC_LEC", "DG_BC", 1.0, 0.39, 0.17},
        {"MEC_DGBC", "EC_MEC", "DG_BC", 1.0, 0.39, 0.17},
        {"DGGC_DGBC", "DG_GC", "DG_BC", 1.0, 0.39, 0.67},
        {"DGMC_DGBC", "DG_MC", "DG_BC", 1.0, 0.39, 0.076},
        {"DGBC_DGBC", "DG_BC", "DG_BC", 1.0, 0.0, 0.8},
        {"DGBCCCK_DGBC", "DG_BCCCK", "DG_BC", 1.0, 0.07, 0.8},
        {"DGHICAP_DGBC", "DG_HICAP", "DG_BC", 1.0, 0.07, 0.8},
        {"DGHIPP_DGBC", "DG_HIPP", "DG_BC", 1.0, 0.0, 0.541},
        {"DGMOPP_DGBC", "DG_MOPP", "DG_BC", 1.0, 0.0, 0.8},
        {"DGTML_DGBC", "DG_TML", "DG_BC", 1.0, 0.0, 0.541},
        {"LEC_DGBCCCK", "EC_LEC", "DG_BCCCK", 1.0, 0.39, 0.1198},
        {"MEC_DGBCCCK", "EC_MEC", "DG_BCCCK", 1.0, 0.39, 0.1198},
        {"DGAAC_DGBCCCK", "DG_AAC", "DG_BCCCK", 1.0, 0.0, 0.5},
        {"DGBC_DGBCCCK", "DG_BC", "DG_BCCCK", 1.0, 0.0, 0.5},
        {"DGBCCCK_DGBCCCK", "DG_BCCCK", "DG_BCCCK", 1.0, 0.07, 0.5},
        {"DGHICAP_DGBCCCK", "DG_HICAP", "DG_BCCCK", 1.0, 0.07, 0.5},
        {"DGHIPP_DGBCCCK", "DG_HIPP", "DG_BCCCK", 1.0, 0.0, 0.362},
        {"DGMOPP_DGBCCCK", "DG_MOPP", "DG_BCCCK", 1.0, 0.0, 0.5},
        {"DGTML_DGBCCCK", "DG_TML", "DG_BCCCK", 1.0, 0.0, 0.362},
        {"LEC_DGHICAP", "EC_LEC", "DG_HICAP", 1.0, 0.39, 0.0451},
        {"MEC_DGHICAP", "EC_MEC", "DG_HICAP", 1.0, 0.39, 0.0451},
        {"DGGC_DGHICAP", "DG_GC", "DG_HICAP", 1.0, 0.39, 0.1824},
        {"DGMC_DGHICAP", "DG_MC", "DG_HICAP", 1.0, 0.39, 0.0092},
        {"DGBC_DGHICAP", "DG_BC", "DG_HICAP", 1.0, 0.0, 0.3},
        {"DGBCCCK_DGHICAP", "DG_BCCCK", "DG_HICAP", 1.0, 0.07, 0.3},
        {"DGHICAP_DGHICAP", "DG_HICAP", "DG_HICAP", 1.0, 0.07, 0.3},
        {"DGHIPP_DGHICAP", "DG_HIPP", "DG_HICAP", 1.0, 0.0, 0.226},
        {"DGMOPP_DGHICAP", "DG_MOPP", "DG_HICAP", 1.0, 0.0, 0.3},
        {"DGTML_DGHICAP", "DG_TML", "DG_HICAP", 1.0, 0.0, 0.226},
        {"DGGC_DGHIPP", "DG_GC", "DG_HIPP", 1.0, 0.39, 0.4328},
        {"DGMC_DGHIPP", "DG_MC", "DG_HIPP", 1.0, 0.39, 0.04958},
        {"DGTML_DGHIPP", "DG_TML", "DG_HIPP", 1.0, 0.0, 0.46},
        {"LEC_DGMOPP", "EC_LEC", "DG_MOPP", 1.0, 0.39, 0.4},
        {"MEC_DGMOPP", "EC_MEC", "DG_MOPP", 1.0, 0.39, 0.4},
        {"DGHIPP_DGMOPP", "DG_HIPP", "DG_MOPP", 1.0, 0.0, 0.64},
        {"DGMOPP_DGMOPP", "DG_MOPP", "DG_MOPP", 1.0, 0.0, 0.9},
        {"DGTML_DGMOPP", "DG_TML", "DG_MOPP", 1.0, 0.0, 0.64},
        {"LEC_DGTML", "EC_LEC", "DG_TML", 1.0, 0.39, 0.21},
        {"MEC_DGTML", "EC_MEC", "DG_TML", 1.0, 0.39, 0.21},
        {"DGHICAP_DGTML", "DG_HICAP", "DG_TML", 1.0, 0.07, 0.9},
        {"DGHIPP_DGTML", "DG_HIPP", "DG_TML", 1.0, 0.0, 0.637},
        {"DGMOPP_DGTML", "DG_MOPP", "DG_TML", 1.0, 0.0, 0.9},
        {"DGTML_DGTML", "DG_TML", "DG_TML", 1.0, 0.0, 0.637},
    };

    spec.optimized_connection_order = {
        "LEC_DGGC",
        "MEC_DGGC",
        "DGMC_DGGC",
        "DGAAC_DGGC",
        "DGBC_DGGC",
        "DGBCCCK_DGGC",
        "DGHICAP_DGGC",
        "DGHIPP_DGGC",
        "DGMOPP_DGGC",
        "DGTML_DGGC",
        "DGGC_DGMC",
        "DGMC_DGMC",
        "DGAAC_DGMC",
        "DGTML_DGMC",
        "LEC_DGAAC",
        "MEC_DGAAC",
        "DGGC_DGAAC",
        "DGMC_DGAAC",
        "DGBC_DGAAC",
        "DGBCCCK_DGAAC",
        "DGHICAP_DGAAC",
        "DGHIPP_DGAAC",
        "DGMOPP_DGAAC",
        "DGTML_DGAAC",
        "LEC_DGBC",
        "MEC_DGBC",
        "DGGC_DGBC",
        "DGMC_DGBC",
        "DGBC_DGBC",
        "DGBCCCK_DGBC",
        "DGHICAP_DGBC",
        "DGHIPP_DGBC",
        "DGMOPP_DGBC",
        "DGTML_DGBC",
        "LEC_DGBCCCK",
        "MEC_DGBCCCK",
        "DGAAC_DGBCCCK",
        "DGBC_DGBCCCK",
        "DGBCCCK_DGBCCCK",
        "DGHICAP_DGBCCCK",
        "DGHIPP_DGBCCCK",
        "DGMOPP_DGBCCCK",
        "DGTML_DGBCCCK",
        "LEC_DGHICAP",
        "MEC_DGHICAP",
        "DGGC_DGHICAP",
        "DGMC_DGHICAP",
        "DGBC_DGHICAP",
        "DGBCCCK_DGHICAP",
        "DGHICAP_DGHICAP",
        "DGHIPP_DGHICAP",
        "DGMOPP_DGHICAP",
        "DGTML_DGHICAP",
        "DGGC_DGHIPP",
        "DGMC_DGHIPP",
        "DGTML_DGHIPP",
        "LEC_DGMOPP",
        "MEC_DGMOPP",
        "DGHIPP_DGMOPP",
        "DGMOPP_DGMOPP",
        "DGTML_DGMOPP",
        "LEC_DGTML",
        "MEC_DGTML",
        "DGHICAP_DGTML",
        "DGHIPP_DGTML",
        "DGMOPP_DGTML",
        "DGTML_DGTML",
    };

    spec.default_fr_targets = {
        {"DG_GC", 0.66}, {"DG_MC", 1.6}, {"DG_BC", 20.0}, {"DG_AAC", 20.0},
        {"DG_BCCCK", 5.0}, {"DG_HICAP", 5.0}, {"DG_HIPP", 20.0},
        {"DG_MOPP", 5.0}, {"DG_TML", 5.0}
    };

    spec.default_fr_bounds = {
        {"DG_GC", {0.55, 0.92}}, {"DG_MC", {0.98, 2.92}},
        {"DG_BC", {15.0, 36.0}}, {"DG_AAC", {15.0, 36.0}},
        {"DG_BCCCK", {1.0, 8.0}}, {"DG_HICAP", {1.0, 8.0}},
        {"DG_HIPP", {4.0, 36.0}}, {"DG_MOPP", {4.0, 25.0}},
        {"DG_TML", {4.0, 25.0}}
    };

    spec.ei_registrations = {
        {"DG_GC",    {0,1,2},       {3,4,5,6,7,8,9}},
        {"DG_MC",    {10,11},       {12,13}},
        {"DG_AAC",   {14,15,16,17}, {18,19,20,21,22,23}},
        {"DG_BC",    {24,25,26,27}, {28,29,30,31,32,33}},
        {"DG_BCCCK", {34,35},       {36,37,38,39,40,41,42}},
        {"DG_HICAP", {43,44,45,46}, {47,48,49,50,51,52}},
        {"DG_HIPP",  {53,54},       {55}},
        {"DG_MOPP",  {56,57},       {58,59,60}},
        {"DG_TML",   {61,62},       {63,64,65,66}}
    };

    spec.default_velocity = 0.13;
    spec.velocity_by_pre_group = { {"EC_MEC", 0.32}, {"EC_LEC", 1.36} };
    spec.ec_to_gc_infra_weight_scale = 1.19;

    return spec;
}

}  // namespace hippomodel::DG
